# Generated by Django 6.0.5 on 2026-06-22 15:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2020)])),
                ('title', models.CharField(default='CSE Spring Fest', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('target_date', models.DateTimeField(blank=True, help_text='Countdown target date/time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('fest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='cse_fest.fest')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='cse_fest/committee/')),
                ('position', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('chief_guest', 'Chief Guest'), ('advisor', 'Advisor'), ('organizer', 'Organizing Committee'), ('problem_setter', 'Problem Setter'), ('volunteer', 'Volunteer')], max_length=20)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('fest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_members', to='cse_fest.fest')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('poster', models.ImageField(blank=True, upload_to='cse_fest/posters/')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('hackathon', 'Hackathon'), ('iupc', 'IUPC'), ('efootball', 'E-Football'), ('ictquiz', 'ICT Quiz')], max_length=20)),
                ('team_size', models.PositiveIntegerField(default=1)),
                ('rule_book_pdf', models.FileField(blank=True, upload_to='cse_fest/rules/')),
                ('registration_open', models.BooleanField(default=True)),
                ('requires_team', models.BooleanField(default=False)),
                ('requires_payment', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('fest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cse_fest.fest')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('fest', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='FestRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('student_id', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('team_name', models.CharField(blank=True, help_text='For group events', max_length=200)),
                ('team_members', models.TextField(blank=True, help_text='Names of team members')),
                ('transaction_id', models.CharField(blank=True, help_text='Payment transaction ID if required', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('agreed_to_rules', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='cse_fest.festevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FestSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('fest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='cse_fest.fest')),
            ],
            options={
                'ordering': ['date', 'time', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_new', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='cse_fest.fest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='cse_fest/sponsors/')),
                ('sponsor_type', models.CharField(choices=[('university', 'University Partner'), ('tech', 'Tech Partner'), ('gold', 'Gold Sponsor'), ('silver', 'Silver Sponsor')], max_length=20)),
                ('url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('fest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='cse_fest.fest')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
