# Generated by Django 6.0.5 on 2026-06-22 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_fest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festevent',
            name='team_size',
        ),
        migrations.RemoveField(
            model_name='festregistration',
            name='team_members',
        ),
        migrations.AddField(
            model_name='festevent',
            name='max_team_size',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='festevent',
            name='min_team_size',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='FestTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='cse_fest.festregistration')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
