# Generated by Django 6.0.5 on 2026-06-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_fest', '0002_remove_festevent_team_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='festevent',
            name='prize_pool',
            field=models.CharField(blank=True, help_text='e.g. 50,000 BDT + Trophies', max_length=200),
        ),
        migrations.AddField(
            model_name='festevent',
            name='registration_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Registration fee in BDT', max_digits=10),
        ),
    ]
