# Generated by Django 6.0.5 on 2026-06-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_fest', '0003_festevent_prize_pool_festevent_registration_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festevent',
            name='rule_book_pdf',
            field=models.URLField(blank=True, help_text='Google Drive link to the rule book PDF'),
        ),
    ]
