# Generated by Django 6.0.5 on 2026-06-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_fest', '0004_alter_festevent_rule_book_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='festregistration',
            name='application_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='festregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
