# Generated by Django 6.0.5 on 2026-06-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_fest', '0005_festregistration_application_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fest',
            name='bkash_number',
            field=models.CharField(blank=True, help_text='bKash number for payment', max_length=20),
        ),
        migrations.AddField(
            model_name='festregistration',
            name='payment_method',
            field=models.CharField(choices=[('physical', 'Physical Payment'), ('bkash', 'bKash')], default='physical', max_length=10),
        ),
        migrations.AlterField(
            model_name='festregistration',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='bKash transaction ID', max_length=100),
        ),
    ]
