# Generated by Django 6.0.5 on 2026-06-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_fest', '0006_fest_bkash_number_festregistration_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='festregistration',
            name='device_name',
            field=models.CharField(blank=True, help_text='Device Name (for eFootball)', max_length=200),
        ),
        migrations.AddField(
            model_name='festregistration',
            name='in_game_name_id',
            field=models.CharField(blank=True, help_text='In-Game Name & ID (for eFootball)', max_length=200),
        ),
        migrations.AddField(
            model_name='festregistration',
            name='self_photo',
            field=models.ImageField(blank=True, help_text='Self photo (for eFootball)', upload_to='cse_fest/selfies/'),
        ),
    ]
