# Generated by Django 6.0.5 on 2026-06-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_fest', '0007_festregistration_device_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='festteammember',
            name='department',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='festteammember',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='festteammember',
            name='semester',
            field=models.CharField(blank=True, help_text='e.g. 4/1', max_length=20),
        ),
        migrations.AddField(
            model_name='festteammember',
            name='student_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='festteammember',
            name='t_shirt_size',
            field=models.CharField(blank=True, choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], max_length=5),
        ),
    ]
