# Generated by Django 6.0.5 on 2026-06-27 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_fest', '0008_festteammember_department_festteammember_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='festregistration',
            name='hackathon_category',
            field=models.CharField(blank=True, help_text='Project category (for hackathon)', max_length=100),
        ),
        migrations.CreateModel(
            name='FestPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text='e.g. Winner, 1st Runners Up', max_length=100)),
                ('amount', models.CharField(help_text='e.g. 1500/- & Trophy', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='cse_fest.festevent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
