# Generated by Django 6.0.5 on 2026-06-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_fest', '0009_festregistration_hackathon_category_festprize'),
    ]

    operations = [
        migrations.AddField(
            model_name='festevent',
            name='hackathon_fee_3',
            field=models.DecimalField(blank=True, decimal_places=2, default=1500, help_text='Hackathon fee for 3-member team', max_digits=10),
        ),
        migrations.AddField(
            model_name='festevent',
            name='hackathon_fee_4',
            field=models.DecimalField(blank=True, decimal_places=2, default=2000, help_text='Hackathon fee for 4-member team', max_digits=10),
        ),
    ]
