# Generated by Django 6.0.5 on 2026-06-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_fest', '0010_festevent_hackathon_fee_3_festevent_hackathon_fee_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='fest',
            name='last_registration_date',
            field=models.DateTimeField(blank=True, help_text='Last date/time for registration', null=True),
        ),
    ]
