# Generated by Django 6.0.5 on 2026-06-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_fest', '0011_fest_last_registration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fest',
            name='last_registration_date',
        ),
        migrations.AddField(
            model_name='festevent',
            name='last_registration_date',
            field=models.DateTimeField(blank=True, help_text='Last date/time for registration (per event)', null=True),
        ),
    ]
