# Generated by Django 6.0.5 on 2026-06-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_fest', '0012_remove_fest_last_registration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fest',
            name='poster',
            field=models.ImageField(blank=True, help_text='Fest poster for homepage card', upload_to='cse_fest/posters/'),
        ),
    ]
