# Generated by Django 6.0.5 on 2026-06-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_fest', '0013_fest_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='festevent',
            name='accent_color',
            field=models.CharField(blank=True, help_text='Auto-extracted accent color from poster', max_length=7),
        ),
        migrations.AddField(
            model_name='festevent',
            name='primary_color',
            field=models.CharField(blank=True, help_text='Auto-extracted dominant color from poster', max_length=7),
        ),
        migrations.AddField(
            model_name='festevent',
            name='secondary_color',
            field=models.CharField(blank=True, help_text='Auto-extracted secondary color from poster', max_length=7),
        ),
    ]
