# Generated by Django 6.0.5 on 2026-06-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_fest', '0014_festevent_accent_color_festevent_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='festevent',
            name='provided_kit',
            field=models.TextField(blank=True, help_text='Items provided to participants (T-shirt, food, certificate, etc.)'),
        ),
    ]
