# Generated by Django 6.0.5 on 2026-06-30 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_fest', '0015_festevent_provided_kit'),
    ]

    operations = [
        migrations.AddField(
            model_name='festschedule',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='cse_fest.festevent'),
        ),
    ]
