# Generated by Django 6.0.5 on 2026-06-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_fest', '0016_festschedule_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='festschedule',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AlterField(
            model_name='festregistration',
            name='department',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='festregistration',
            name='student_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='festregistration',
            name='university',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
