# Generated by Django 6.0.5 on 2026-06-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_fest', '0017_alter_festschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festregistration',
            name='university',
            field=models.CharField(blank=True, default='BAIUST', max_length=200),
        ),
    ]
