# Generated by Django 6.0.5 on 2026-06-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_fest', '0018_alter_festregistration_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='festregistration',
            name='group',
            field=models.CharField(blank=True, choices=[('G1', 'G1'), ('G2', 'G2')], max_length=5),
        ),
        migrations.AddField(
            model_name='festregistration',
            name='section',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=5),
        ),
        migrations.AddField(
            model_name='festteammember',
            name='group',
            field=models.CharField(blank=True, choices=[('G1', 'G1'), ('G2', 'G2')], max_length=5),
        ),
        migrations.AddField(
            model_name='festteammember',
            name='section',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=5),
        ),
    ]
