# Generated by Django 6.0.5 on 2026-07-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_fest', '0019_festregistration_group_festregistration_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='festregistration',
            name='semester',
            field=models.CharField(blank=True, help_text='e.g. 4/1', max_length=20),
        ),
    ]
