# Generated by Django 6.0.5 on 2026-05-15 16:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def generate_uuids(apps, schema_editor):
    Profile = apps.get_model('portal', 'Profile')
    for profile in Profile.objects.all():
        profile.member_uuid = uuid.uuid4()
        profile.save(update_fields=['member_uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_profile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='member_uuid',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(generate_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='profile',
            name='member_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes for rejection or approval')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
