# Generated by Django 6.0.5 on 2026-06-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_profile_is_member_profile_member_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('panel', models.CharField(choices=[('advisory', 'Advisory Panel'), ('leading', 'Leading Panel'), ('tech', 'Tech Panel'), ('social_media', 'Social Media & Relations Panel'), ('executive', 'Executive Members')], max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('avatar_letter', models.CharField(blank=True, max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['panel', 'order'],
            },
        ),
    ]
