# Generated by Django 6.0.5 on 2026-06-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_teammember_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='department',
            field=models.CharField(blank=True, default='CSE', max_length=50),
        ),
    ]
