# Generated by Django 6.0.5 on 2026-06-13 17:09

import portal.models
from django.db import migrations, models


def dummy_path(instance, filename):
    return f'qr_codes/{filename}'


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_teammember_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qr_code',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=dummy_path),
        ),
    ]
