# Generated by Django 6.0.5 on 2026-06-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_profile_email_alter_profile_phone_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='profile',
            name='qr_png',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
