# Generated by Django 6.0.5 on 2026-06-13 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_remove_profile_qr_code_profile_qr_png'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MembershipApplication',
        ),
    ]
