# Generated by Django 6.0.5 on 2026-06-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_delete_membershipapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='claimed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='expires_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
