# Generated by Django 6.0.5 on 2026-06-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_profile_claimed_at_profile_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='panel',
            field=models.CharField(choices=[('advisory', 'Advisory Panel'), ('leading', 'Leading Panel'), ('tech', 'Tech Panel'), ('social_media', 'Social Media & Relations Panel'), ('treasurer', 'Treasurer Panel'), ('organizing', 'Organizing Panel'), ('executive', 'Executive Members')], max_length=20),
        ),
    ]
