# Generated by Django 6.0.5 on 2026-06-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_alter_teammember_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='leader_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teammember',
            name='leader_position',
            field=models.CharField(blank=True, choices=[('president', 'President'), ('general_secretary', 'General Secretary'), ('vice_president', 'Vice President')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='github',
            field=models.URLField(blank=True, default='https://github.com/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='linkedin',
            field=models.URLField(blank=True, default='https://linkedin.com/'),
        ),
    ]
