# Generated by Django 6.0.5 on 2026-05-16 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='payment_method',
            field=models.CharField(choices=[('bkash', 'bKash'), ('offline', 'Offline/Physical')], default='bkash', max_length=20),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='payment_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='payment_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='bKash transaction number', max_length=50),
        ),
    ]
