# Generated by Django 6.0.5 on 2026-05-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventregistration_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requires_payment',
            field=models.BooleanField(default=True, help_text='If unchecked, no payment is needed for this event'),
        ),
        migrations.AddField(
            model_name='event',
            name='requires_registration',
            field=models.BooleanField(default=True, help_text='If unchecked, event is open to all without registration'),
        ),
    ]
